/** @type {import('tailwindcss').Config} */
import forms from '@tailwindcss/forms';

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary-fixed-dim': '#9de0e1',
        'error-container': '#fe8983',
        'tertiary-container': '#dbfce5',
        'primary-dim': '#0b5c5d',
        'surface-container-low': '#f1f4f6',
        'secondary-container': '#cbe7f5',
        'on-error-container': '#752121',
        error: '#9f403d',
        'surface-container-highest': '#dbe4e7',
        'on-error': '#fff7f6',
        'secondary-fixed-dim': '#bdd9e6',
        'surface-dim': '#d1dce0',
        'tertiary-fixed-dim': '#ccedd7',
        'on-surface-variant': '#586064',
        'inverse-on-surface': '#9b9d9e',
        'tertiary-dim': '#3d5949',
        'on-primary': '#d9ffff',
        background: '#f8f9fa',
        'tertiary-fixed': '#dbfce5',
        'inverse-primary': '#b8fdfd',
        'on-background': '#2b3437',
        'error-dim': '#4e0309',
        'inverse-surface': '#0c0f10',
        'on-secondary-fixed-variant': '#455f6b',
        'on-secondary-fixed': '#29434e',
        'surface-container': '#eaeff1',
        surface: '#f8f9fa',
        'on-tertiary-fixed-variant': '#4f6d5b',
        'on-primary-container': '#095b5c',
        'surface-container-lowest': '#ffffff',
        outline: '#737c7f',
        'on-tertiary-container': '#456251',
        'on-secondary-container': '#3c5561',
        'outline-variant': '#abb3b7',
        'primary-fixed': '#aaefef',
        'secondary-fixed': '#cbe7f5',
        'surface-container-high': '#e3e9ec',
        primary: '#1f6869',
        'on-surface': '#2b3437',
        'on-secondary': '#f2faff',
        'primary-container': '#aaefef',
        'surface-bright': '#f8f9fa',
        'on-primary-fixed-variant': '#1b6566',
        tertiary: '#486554',
        'secondary-dim': '#3d5762',
        'surface-tint': '#1f6869',
        secondary: '#49636f',
        'surface-variant': '#dbe4e7',
        'on-tertiary-fixed': '#33503f',
        'on-tertiary': '#e6ffed',
        'on-primary-fixed': '#004748',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [forms],
}
